# Generated by Django 2.0.4 on 2018-04-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('termino', models.DateTimeField(blank=True)),
                ('estado', models.CharField(choices=[('terminada', 'Terminada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada'), ('limite', 'Limite')], default='pendiente', max_length=30)),
                ('img', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
