# Generated by Django 2.0.4 on 2018-04-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180413_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='inicio',
            field=models.DateTimeField(),
        ),
    ]
